### ISSUE TITLE
Some interesting results...

### ISSUE THREAD

**Issue by Truncated** [GeneralHuli/HeroLab-Importer#2]
My first transfer came over pretty well!

Couple of things but I wanted to touch base with you first to see if maybe I missed something before I split anything out:
1. Ancestry of Orcish didn't get transferred (just blank), butt Dromaar Heritage, Background, Class, and Deity all did fine.
2. Picture didn't come over, but it wasn't clear if it was supposed to.
3. Coins did not come over (just some SP & CP).
4. I _think_ a regular pouch with three items in it (10 pieces of chalk, flint & steel, and soap) appears have become a Cloud Pouch and Cold Comfort (Greater)...? I'm going by its the only thing actually missing from the list. I assume it's due to how the inventory presents items within containers...
5. I put the add-on in debug mode from the start because I know what a challenge this is, but the output I got didn't help me at all. Is there any advice you can provide for better feedback on what is coming in from HeroLab and what part of the add-on eval is giving these errors?
![image](https://github.com/GeneralHuli/HeroLab-Importer/assets/14208325/f4c401f5-e5c8-4dc0-b6f2-05e3f4cbb428)

Is there some raw dump that can be found or enabled to see what is having false-positives or erroring out?
Maybe a way to pull and save the raw character input easily in Foundry?

I think a notification can be set to stay on while the call to HeroLab is processing to give a "loading" notice, btw. I'm not a programmer either but I'm down with trying to help troubleshoot and improve what I can for this.

**Comment by Truncated** [comment]
Nm on the wealth; I forgot this from before. Evidently, they never got to the bug report... :(
![image](https://github.com/GeneralHuli/HeroLab-Importer/assets/14208325/a8a0312e-dbc9-44ec-a747-897dfaeab3aa)

**Comment by GeneralHuli** [comment]
Thanks for giving some feedback! I'll go over each of your points.

1. I didn't test test every ancestry/class, because I couldn't, but I will look at orcish and try and see what is going on. It seems weird that it wouldn't import correctly. 
2. Hero Lab doesn't export your picture, so I can't import it, unfortunately. I'll update the readme to clarify that.
3. I realized a few days ago that I completely forgot to import money! I haven't gotten around to it yet, but that is first on the agenda for tomorrow. Woops 
4. I assume there is a discrepancy with Hero Lab and Foundry naming and it took your "pouch" and found "cloud pouch". I'll look into that. The others, I have no idea yet. Those three items import normally on my tests. Could be the imbedded objects, like you said.
5. The errors don't actually come from my module, but mine is the cause. I saw these before when an item gets added to the actor in Foundry and can't resolve the Rules Element correctly. Yours is because your Dromaar heritage doesn't have the Orcish ancestry to resolve itself.

I can't detect false-positives (if I could, there wouldn't be any, lol) so I can't give any output for them, but you did give me the idea to output some objects, while in debug, that give a list of what was exported vs. what is imported. Not sure about a loading screen, but I think there should be a popup at the end, stating it's finished, and any items that it couldn't find any matches for.
I will work on these all tomorrow and let you know when an update is released. If you could, please attach the json for your character, from Hero Labs. (In the Export/Integrate window is a dropdown for Manual Export that will give you a file. Indecently, this is the data that is read from my module, if you are curious as to what information I have to work with.) I will use this to test and make sure I can solve all your issues.

**Comment by Truncated** [comment]
> Is there some raw dump that can be found or enabled to see what is having false-positives or erroring out?

Sorry this wasn't clear - I meant was there a raw dump that showed the hero lab data and where your module applied to it so that it could be _manually inspected_ for false-positives to resolve. :)

**Comment by GeneralHuli** [comment]
Ok, I've got some of the kinks worked out. Wealth is now added. Reworked quite a bit of the debug logs and added an ending log that outputs an object that links the exported items to what the system finds as a match.
I figured out that I HAD tested Orc as an Ancestry, and didn't have a problem. I even changed the Heritage to Dromaar. Also, Pathfinder 2e doesn't have a 'Pouch', at least not that I can find in Foundry or Hero Lab. If you made a custom container in HL, it won't import correctly, unless you create the same item in the Foundry Pathfinder equipment compendium.

With all that said, I can't troubleshoot your Dromaar issues unless I get your exported JSON data from HL.

**Comment by Truncated** [comment]
I am pretty sure there were no custom things made, but I'll double check. I'm testing with characters that were made for my campaign by others while they were exploring the system. We just switched from 1e to 2e, so there's plenty I don't know yet.

I'll take another pass at the same character and see what happens, then return with whatever I can gather.
